"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my honor, Dharnish Muralidharan, this 
programming assignment is my own work and I have not provided this code to 
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: dm55786
UT EID 2:
"""


# TODO: implement this function. You may delete this comment when you are done.
def length_of_longest_substring_n3(s):
    """
    Finds the length of the longest substring without repeating characters
    using a brute force approach (O(N^3)).

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    max_length = 0
    for i in range(len(s)):
        for j in range(i, len(s)):
            freq_list = [0] * 256
            substring = s[i:j+1]
            for char in substring:
                freq_list[ord(char)] += 1
            if max(freq_list) <= 1 and len(substring) > max_length:
                max_length = len(substring)
    return max_length
    

                


# TODO: implement this function. You may delete this comment when you are done.
def length_of_longest_substring_n2(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N^2)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    max_length = 0
    for i in range(len(s)):
        freq_list = [0] * 256
        for j in range(i, len(s)):
            freq_list[ord(s[j])] += 1
            if max(freq_list) <= 1 and j - i + 1 > max_length:
                max_length = j - 1 + 1
    return max_length


# TODO: implement this function. You may delete this comment when you are done.
def length_of_longest_substring_n(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list. However, this approach stops early, breaking out of the inner
    loop when a repeating character is found. You may also choose to challenge
    yourself by implementing a sliding window approach.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    max_length = 0
    for i in range(len(s)):
        freq_list = [0] * 256
        for j in range(i, len(s)):
            freq_list[ord(s[j])] += 1
            if freq_list[ord(s[j])] > 1:
                break
            if j - i + 1 > max_length:
                max_length = j - 1 + 1
    return max_length
